### ISSUE TITLE
mpileup problem

### ISSUE THREAD

**Issue by napobo3** [tkrahn/extract23#2]
It looks like the samtools mpileup doesn't do the job. 
Any ideas ?

> samtools mpileup -C 50 -v -l 23andMe_V3_hg19_ref.tab.gz -f hs37d5.fasta 1.bam > 23andMe_raw.vcf.gz

samtools :

> $ samtools --version
> samtools 1.3
> Using htslib 1.3
> Copyright (C) 2015 Genome Research Ltd.

The 23andMe_raw.vcf looks like :
```
##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##samtoolsVersion=1.2+htslib-1.2.1
##samtoolsCommand=samtools mpileup -C 50 -v -l 23andMe_V3_hg19_ref.tab.gz -f hs37d5.fasta 1.bam
##reference=file://hs37d5.fasta
##contig=<ID=1,length=249250621>
<...>
##INFO=<ID=MQ0F,Number=1,Type=Float,Description="Fraction of MQ0 reads (smaller is better)">
##INFO=<ID=I16,Number=16,Type=Float,Description="Auxiliary tag used for calling, see description of bcf_callret1_t in bam2bcf.h">
##INFO=<ID=QS,Number=R,Type=Float,Description="Auxiliary tag used for calling">
##FORMAT=<ID=PL,Number=G,Type=Integer,Description="List of Phred-scaled genotype likelihoods">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  777

```

**Comment by tkrahn** [comment]
Good, it seems like your samtools version uses htslib.
I assume you use a WGS BAM file from FGC. Then you'll need to convert the 23andMe_V3_hg19_ref.tab.gz file as mentioned in the readme:
```
gunzip -c 23andMe_V3_hg19_ref.tab.gz > 23andMe_V3_hg19_ref.tab
cat 23andMe_V3_hg19_ref.tab | sed 's/^chr//' > 23andMe_V3_GRCh37_ref.tab
bgzip -c 23andMe_V3_GRCh37_ref.tab > 23andMe_V3_GRCh37_ref.tab.gz
tabix -s1 -b2 -e2 23andMe_V3_GRCh37_ref.tab.gz
```
This is because the GRCh37 format uses 1, 2, 3 ... 22, M, X, Y instead of chr1, chr2, ... chr22, chrM, chrX and chrY.

**Comment by napobo3** [comment]
Now it works, thanks.
