### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Griz054** [tkrahn/extract23#7]
I could have sent an e-mail but I figured I'd ask the question here. I'm working with some folks that read my article about this entire process. One question that came up - in the script why didn't you just use the vcf to populate the data instead of grabbing the larger bam file?

**Comment by tkrahn** [comment]
Sorry for my late reply. The VCF may not tell me if a certain SNP is covered by sequencing reads. It may be covered by reads and just match the reference sequence or it may not be covered meaning a nocall.

So you'd at least need additional information from a BED file. Yet the BED file doesn't tell you the quality of the reads at each position, it just defines sections of the genome that are defined trust-worthy. This may have its quirks if just a single base in the middle of a BED region has quality issues. So using BED files comes with a lot of complicated questions. Therefore I have decided that the cleanest way is to directly score the SNPs from the BAM file.

**Comment by Griz054** [comment]
Thank you. I knew you had a reason. I just couldn't tell him what it was.

Jim "Griz" Adams
