### ISSUE TITLE
Not works with some data from ncbi

### ISSUE THREAD

**Issue by RasulSrg** [tkrahn/extract23#8]
https://www.ncbi.nlm.nih.gov/sra/?term=SRP132561
Cant extract any data from bam files which are made of fastq using latest BWA and samtools. Ref. fasta is latest GRchr37.75. But "Bam analysis kit" extracts autosomal with no problem.

**Comment by tkrahn** [comment]
Please make sure that you map the fastq reads against hg19 and NOT GRCh37. There are tiny differences in the nomenclature.

If for some reason you must use GRCh37, then you also need to convert 23andMe_V3_hg19_ref.tab.gz in the GRCh37 format as I've described it in the "Requirements" section. Then it should work.

**Comment by RasulSrg** [comment]
> Please make sure that you map the fastq reads against hg19 and NOT GRCh37. There are tiny differences in the nomenclature.
> 
> If for some reason you must use GRCh37, then you also need to convert 23andMe_V3_hg19_ref.tab.gz in the GRCh37 format as I've described it in the "Requirements" section. Then it should work.

thank you, i am sorry, i am new to bioinformatics. delete my issue message please

**Comment by tkrahn** [comment]
No problem, the different versions of the reference sequences are not always intuitive.
